import turtle
monty = turtle.Turtle()
monty.shape("turtle")

monty.fillcolor('blue')
monty.begin_fill()
monty.forward(100)
monty.left(90)
monty.forward(100)
monty.left(90)
monty.forward(100)
monty.left(90)
monty.forward(100)
monty.left(90)
monty.end_fill()

monty.penup()
monty.goto(-100,200)
monty.write("Latający")
monty.goto(200,200)
monty.write("Żółw")
monty.goto(-100,-100)
monty.write("Monty")
monty.goto(200,-100)
monty.write("Pythona")
in range (5)
